name: Android CI

on:
  push:
    branches: [ "main" ]


jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: setup jdk
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Bump version
      uses: chkfung/android-version-actions@v1.1
      with:
        gradlePath: app/build.gradle # or app/build.gradle.kts 
        versionCode: ${{github.run_number}}
    - name: Build Release APK
      run: ./gradlew assembleDebug
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        generate_release_notes: true
        token: ${{ secrets.TOKEN }}
          
